sources:
  include:
    - ../SwiftyMocky-Example/Shared
    - ../SwiftyMocky-Example/iOS
    - ../SwiftyMocky-Tests/iOS
  exclude:
    - ../SwiftyMocky-Example/Shared/Other/Excluded.generated.swift
templates:
  - ../Sources/SwiftyMocky
output:
  ../SwiftyMocky-Tests/iOS/Mocks
args:
  swiftyMocky:
    import:
      - CoreGraphics
      - Foundation
      - UIKit
    testable:
      - Mocky_Example_iOS
    excludedSwiftLintRules:
      - force_cast
      - function_body_length
      - line_length
      - vertical_whitespace
