name: Build & Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  SwiftyMocky-Tests:
    runs-on: macos-13-xlarge
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.3.1'
      - name: Prepare for tests
        run: |
          rake pods
          rake mock
      - name: Run tests iOS
        run: |
          fastlane ios test
      - name: Run tests tvOS
        run: |
          fastlane tvos test
      - name: Run tests SwiftPM
        run: |
          swift test
